package Ass2CORBA;


/**
* Ass2CORBA/DCMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/quocminhvu/Documents/workspace/IdeaProjects/COMP6231_Project/Ass2.CORBA/src/CORBA.idl
* Wednesday, August 2, 2017 4:56:32 o'clock PM EDT
*/

public interface DCMSOperations 
{
  String createTRecord (String managerID, String firstName, String lastName, String address, String phone, String specialization, String location);
  String createSRecord (String managerID, String firstName, String lastName, String coursesRegistered, String status);
  String getRecordCounts (String managerID);
  boolean editRecord (String managerID, String recordID, String fieldName, String newValue);
  boolean transferRecord (String managerID, String recordID, String remoteCenterServerName);
  String printAllRecords (String managerID);
  String printRecord (String managerID, String recordID);
  void startUDPServer ();
} // interface DCMSOperations
