package Ass2CORBA;

/**
* Ass2CORBA/DCMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/quocminhvu/Documents/workspace/IdeaProjects/COMP6231_Project/Ass2.CORBA/src/CORBA.idl
* Wednesday, August 2, 2017 4:56:32 o'clock PM EDT
*/

public final class DCMSHolder implements org.omg.CORBA.portable.Streamable
{
  public Ass2CORBA.DCMS value = null;

  public DCMSHolder ()
  {
  }

  public DCMSHolder (Ass2CORBA.DCMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Ass2CORBA.DCMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Ass2CORBA.DCMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Ass2CORBA.DCMSHelper.type ();
  }

}
