package Ass2CORBA;


/**
* Ass2CORBA/DCMSHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/quocminhvu/Documents/workspace/IdeaProjects/COMP6231_Project/Ass2.CORBA/src/CORBA.idl
* Wednesday, August 2, 2017 4:56:32 o'clock PM EDT
*/

abstract public class DCMSHelper
{
  private static String  _id = "IDL:Ass2CORBA/DCMS:1.0";

  public static void insert (org.omg.CORBA.Any a, Ass2CORBA.DCMS that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Ass2CORBA.DCMS extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Ass2CORBA.DCMSHelper.id (), "DCMS");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Ass2CORBA.DCMS read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DCMSStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Ass2CORBA.DCMS value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Ass2CORBA.DCMS narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Ass2CORBA.DCMS)
      return (Ass2CORBA.DCMS)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Ass2CORBA._DCMSStub stub = new Ass2CORBA._DCMSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Ass2CORBA.DCMS unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Ass2CORBA.DCMS)
      return (Ass2CORBA.DCMS)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Ass2CORBA._DCMSStub stub = new Ass2CORBA._DCMSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
