package Ass2CORBA;


/**
* Ass2CORBA/DCMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/quocminhvu/Documents/workspace/IdeaProjects/COMP6231_Project/Ass2.CORBA/src/CORBA.idl
* Wednesday, August 2, 2017 4:56:32 o'clock PM EDT
*/

public interface DCMS extends DCMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DCMS
