package org.omg.CORBA;


/**
* org/omg/CORBA/DCMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/quocminhvu/Documents/workspace/IdeaProjects/COMP6231_Project/Ass2.Minh/src/CORBA.idl
* Friday, July 21, 2017 11:13:50 o'clock AM EDT
*/

public interface DCMS extends DCMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DCMS
