package org.omg.CORBA;


/**
* org/omg/CORBA/DCMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/quocminhvu/Documents/workspace/IdeaProjects/COMP6231_Project/Ass2.Minh/src/CORBA.idl
* Thursday, July 20, 2017 6:39:13 o'clock PM EDT
*/

public interface DCMS extends DCMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DCMS
