package org.omg.CORBA;


/**
* org/omg/CORBA/DCMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/quocminhvu/Documents/workspace/IdeaProjects/COMP6231_Assignment02/src/CORBA.idl
* Tuesday, June 27, 2017 3:20:09 o'clock PM EDT
*/

public interface DCMS extends DCMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DCMS
