package org.omg.CORBA;


/**
* org/omg/CORBA/DCMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/quocminhvu/Documents/workspace/IdeaProjects/COMP6231_Project/Ass2.Minh/src/CORBA.idl
* Friday, July 21, 2017 11:13:50 o'clock AM EDT
*/

public interface DCMSOperations 
{
  String createTRecord (String managerID, String firstName, String lastName, String address, String phone, String specialization, String location);
  String createSRecord (String managerID, String firstName, String lastName, String coursesRegistered, String status);
  String getRecordCounts (String managerID);
  boolean editRecord (String managerID, String recordID, String fieldName, String newValue);
  boolean transferRecord (String managerID, String recordID, String remoteCenterServerName);
  String getRecordType (String recordID);
  void startUDPServer ();
  String printAllRecords ();
  String printRecord (String managerID, String recordID);
} // interface DCMSOperations
