package FrontEnd;


/**
* FrontEnd/FE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/quocminhvu/Documents/workspace/IdeaProjects/COMP6231_Project/src/FrontEnd.idl
* Monday, July 31, 2017 2:38:49 o'clock PM EDT
*/

public interface FE extends FEOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FE
