package FrontEnd;


/**
* FrontEnd/FEHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/quocminhvu/Documents/workspace/IdeaProjects/COMP6231_Project/src/FrontEnd.idl
* Friday, July 21, 2017 9:43:46 o'clock PM EDT
*/

abstract public class FEHelper
{
  private static String  _id = "IDL:FrontEnd/FE:1.0";

  public static void insert (org.omg.CORBA.Any a, FrontEnd.FE that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FrontEnd.FE extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FrontEnd.FEHelper.id (), "FE");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FrontEnd.FE read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FEStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FrontEnd.FE value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FrontEnd.FE narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FrontEnd.FE)
      return (FrontEnd.FE)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FrontEnd._FEStub stub = new FrontEnd._FEStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FrontEnd.FE unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FrontEnd.FE)
      return (FrontEnd.FE)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FrontEnd._FEStub stub = new FrontEnd._FEStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
