package FrontEnd;


/**
* FrontEnd/FEOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/quocminhvu/Documents/workspace/IdeaProjects/COMP6231_Project/src/FrontEnd.idl
* Friday, July 28, 2017 2:41:09 o'clock PM EDT
*/

public interface FEOperations 
{
  String createTRecord (String managerID, String firstName, String lastName, String address, String phone, String specialization, String location);
  String createSRecord (String managerID, String firstName, String lastName, String coursesRegistered, String status);
  String getRecordCounts (String managerID);
  String editRecord (String managerID, String recordID, String fieldName, String newValue);
  String transferRecord (String managerID, String recordID, String remoteCenterServerName);
  String printRecord (String managerID, String recordID);
  String printAllRecords (String managerID);
} // interface FEOperations
