package HelloApp;


/**
* HelloApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/rodmm/IdeaProjects/COMP6231_Project/Ass2.Rodolfo_Kenlo/src/Hello.idl
* Monday, July 31, 2017 5:19:29 PM EDT
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
