package HelloApp;


/**
* HelloApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/kenlo/Documents/IntelliJ/A2Corba/src/Hello.idl
* Sunday, July 9, 2017 5:28:47 o'clock PM EDT
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
