package HelloApp;


/**
* HelloApp/IDLArrayListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/kenlo/Documents/IntelliJ/A2Corba/src/Hello.idl
* Sunday, July 9, 2017 5:28:47 o'clock PM EDT
*/

public final class IDLArrayListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public IDLArrayListHolder ()
  {
  }

  public IDLArrayListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.IDLArrayListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.IDLArrayListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.IDLArrayListHelper.type ();
  }

}
