package DSassg2;


/**
* DSassg2/ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/quocminhvu/Documents/workspace/IdeaProjects/COMP6231_Project/Ass2.Kamal/src/ServerInterface.idl
* Wednesday, August 2, 2017 11:04:15 o'clock AM EDT
*/

public interface ServerInterfaceOperations 
{
  String createTRecord (String manager_id, String f_name, String l_name, String addr, String number, String spec, String loc);
  String createSRecord (String manager_id, String f_name, String l_name, String courselist, String status);
  String getRecordCount (String manager_id);
  String printAllRecords (String managerID);
  String printRecord (String managerID, String recordID);
  boolean edit (String manager_id, String id, String field_name, String value);
  boolean transferRecord (String manager_id, String record_id, String remoteCenterServerName);
} // interface ServerInterfaceOperations
