package DSassg2;


/**
* DSassg2/ServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/quocminhvu/Documents/workspace/IdeaProjects/COMP6231_Project/Ass2.Kamal/src/ServerInterface.idl
* Monday, July 31, 2017 8:16:37 o'clock PM EDT
*/

public interface ServerInterface extends ServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInterface
